export const constantValues = {
    GOOGLE_PLACE_API: 'https://maps.googleapis.com/maps/api/place/autocomplete/json?',
    GOOGLE_API_KEY: 'AIzaSyDao5jHYWwwCyJPmIf_qFlWVvSvUePHM_4',
    APPLICATION_TITLE: 'BillionBrix',
    BASE_URL: 'http://localhost:3000/',
    //BASE_URL1: 'http://ec2-3-145-213-17.us-east-2.compute.amazonaws.com:8081/',
    BASE_URL1: 'http://ec2-3-140-244-24.us-east-2.compute.amazonaws.com:8081/',
    INPUT_DETAILS: 'input',
    INPUT_DETAILS1: 'titlecalculatorservice/get-company-details',
    INPUT_REQUEST: 'titlecalculatorservice/get-titlequote-details',
    SELLER_NET_SHEET_INPUT_DETAILS: 'sellernetsheetinput',
    BUYER_NET_SHEET_INPUT_DETAILS: 'buyernetsheetinput',
    SUMMARY: 'summary',
    SELLER_NET_SHEET: 'sellerNetSheet',
    VIRTUAL_ASSISTANT: 'Hi, I\'m Sophie, your Virtual escrow assistant.\nLet\'s get started on your Title and Settlement quote.',
    SELLER_VIRTUAL_ASSISTANT: 'Hi, I\'m Sophie, your Virtual escrow assistant.\nLet me tell you in seconds how much you\'ll net from your home-sale!',
    LOCATION_INSTRUCTION: 'I\'ll get you a quote in seconds! ',
    SELLER_LOCATION_INSTRUCTION: 'Smart Choice! This branch of ours has one of the lowest fees in town!',
    TRANSACTION_TYPE_INSTRUCTION: 'Great! Now that we found your property, it\'s just a few more steps!',
    INSURENCE_PAID_INSTRUCTION_CASH_FINANCE: 'Awesome! Last couple questions before I present you with your quote.',
    INSURENCE_PAID_INSTRUCTION_OTHERS: 'Awesome! Last couple questions before I present you with your quote.\n Let\'s see if I can get you any insurance premium credit!',
    AMOUNT_INSTRUCTION: 'Oh! We are at last stage now!!!',
    BRANCH_DROPDOWN_LABEL1: 'Tell me which branch of ',
    BRANCH_DROPDOWN_LABEL2: ' is handling your closing',
    LOCATION_LABEL: 'What\'s your property address?',
    TRANSACTION_TYPE_LABEL: 'Are you buying or refinancing?',
    INSURENCE_PAID_LABEL: 'Who pays for Owner\'s Title  policy',
    REFINANCE_LABEL: 'How long ago did you last finance your home?',
    MORTGAGE_INSTRUCTION: 'Did you know that more than half of american homeowners have mortgages?',
    COMMISSION_INSTRUCTION: 'Awesome! Halfway done! Just a few more steps to go!',
    HOA_INSTRUCTION: 'Millions of americans live in homes that are part of Homeowner\'s Association.',
    PROPERTY_TAX_INSTRUCTION: 'Did you know that local governments in the United States collect more than half a trillion dollars every year in Property Tax?',
    OTHER_INFO_INSTRUCTION: 'Ready? Before hitting \'Calculate\' button below, quickly review these potential costs and enter any amount that applies to this home sale.',
    TRANSACTION_TYPE: 'Tell me about your transaction Type',
    LOAN_TERM: 'Please select your loan term',
    LOAN_TYPE: 'Please select a loan type',
    DOWN_PAYMENT: 'How much you will down payment for the house',
    MIP_FINANCED: 'Is the Mortgage Insurance Premium (MIP) financed?',
    LOAN_TYPE_INSTRUCTION: 'Few More steps to go.',
    HOME_INSURENCE_INSTRUCTION: 'Just few more steps to go!',
    HOA_BUYER_INSTRUCTION: 'Few More steps to go.',
    PROPERTY_TAX_BUYER_INSTRUCTION: 'Almost there! Let me know about your property tax',
    LENDER_FEES_INSTRUCTION: 'Tell me about your Lender fees',
    OTHER_INFO_BUYER_INSTRUCTION: 'Ready to get your estimation! Please hit the Calculate button. But before that check if you have any other expanses',
    EDIT_FIELD: 'Do you want to edit the field?',
    LOCATION_NEXT_TEXT1: 'I\'m ',
    LOCATION_NEXT_TEXT2: 'ready',
    LOCATION_NEXT_TEXT3: ' for the next step when you are.',
    CLICK_HERE: 'Click here',
    SALE_PRICE_NEXT_TEXT: 'I\'m ready for the next step when you are',
    LOAN_TYPE_TEXT: 'If you\'re done entering all details,',
    HOME_INSURENCE_TEXT: 'If you\'re done entering all details,',
    PROPERTY_TAX_TEXT: 'If you\'re done entering all details,',
    LENDER_FEE_TEXT: 'If you\'re done entering all details,',
    MORTGAGE_TEXT: 'I\'m ready for the next step when you are',
    COMMISSION_TEXT: 'I\'m ready for the next step when you are',
    EDIT_CONFIRMATION_MESSAGE: 'Do you want to edit the field?',
    EDIT_CONFIRMATION_MESSAGE_SUBCONTENT: 'Note: Your inputs/answers to subsequent questions will be reset/erased if you choose \'Yes\'',
    LOCATION_PLACEHOLDER: 'Street Address, City, State',
    APT_PLACEHOLDER: 'APT/UNIT#',
    //////// Collpase Span ///////////
    BRANCH_SPAN: 'Branch:',
    LOCATION_SPAN: 'Location:',
    TRANSACTION_TYPE_SPAN: 'Transaction Type:',
    REFINANCE_OPTION_SPAN: 'Refinance:',
    TITLE_INSURENCE_OWNER_SPAN: 'Title Insurance Owner:',
    LOAN_AMOUNT_SPAN: 'Current Loan Balance:',
    NEW_LOAN_AMOUNT_SPAN: 'New Loan Amount:',
    SALES_PRICE_SPAN: 'Sale Price:',
    CLOSING_DATE_SPAN: 'Closing Date:',
    NO_MORTGAGE_SPAN: 'No Mortgage',
    FIRST_MORTGAGE_SPAN: '1st Mortgage:',
    SECOND_MORTGAGE_SPAN: '2nd Mortgage:',
    LISTING_AGENT_COMMISSION_SPAN: 'Listing Agent commission:',
    BUYER_AGENT_COMMISSION_SPAN: 'Buyer\'s agent commission:',
    NO_HOA_SPAN: 'No HOA Due',
    HOA_DUE_SPAN: 'HOA Due:',
    PER_MONTH_SPAN: 'per Month',
    PER_QUARTER_SPAN: 'per Quater',
    PER_YEAR_SPAN: 'per Year',
    PROPERTY_TAX_SPAN: 'PropertyTax:',
    LENDER_ORIGINATION_FEES: 'Lender Origination fees:',
    APPRISAL: 'Apprisal:',
    CREDIT_REPORT: 'Credit Report:',
    TAX_SERVICES: 'Tax Services:',
    FLOOD_CERTIFICATE: 'Flood Certificate:',
    LENDER_INSPECTION_FEE: 'Lender inspection fee:',
    PROCESSING_FEE_FEES: 'Processing fee fees:',
    UNDERWRITER_FEES: 'UnderWriter fees:',
    MORTGAGE_BROKER_FEES: 'Mortgage broker fees:',
    OTHER_FEES: 'Other fees:',
    LOAN_TYPE_SPAN: 'Loan Type:',
    LOAN_TERM_SPAN: 'Loan Term:',
    INTEREST_RATE_SPAN: 'Interest Rate:',
    MIP_RATE_SPAN: 'MIP Rate:',
    PMI_RATE_SPAN: 'PMI Rate:',
    MIP_FINANACE_SPAN: 'MIP Finance:',
    VA_FUNDING_SPAN:'VA Funding:',
    QUOTE_SUMMARY_REVIEW_REQUEST: 'Review and request extra coverage',
    QUOTE_SUMMARY_ENDORSEMENT_RECOMMENDATION: 'Recommended: Take a close look at these endorsements and request additional coverage. We have already added the ones required by most lenders.',
    BUYER: 'Buyer',
    TITLE_QUOTE_PROVIDED: 'Title Quote provided by',
    CONVERSATION_SUMMARY: 'Conversation Summary',
    SELLER: 'Seller',
    CONFIRM_MODAL: 'Do you want to confirm?',
    ///////////////////////////////////////////////////// LENDER FEES IDS////////////////////////

    LENDER_FEES_Lender_Origination_Fees: '1',
    LENDER_FEES_Apprisal: '2',
    LENDER_FEES_Credit_Report: '3',
    LENDER_FEES_Tax_Services: '4',
    LENDER_FEES_Flood_Certificate: '5',
    LENDER_FEES_Lender_Inspection_Fee: '6',
    LENDER_FEES_Processing_Fee_Fees: '7',
    LENDER_FEES_UnderWriter_Fees: '8',
    LENDER_FEES_Mortgage_Broker_Fees: '9',
    LENDER_FEES_Other_Fees: '10',

    ///////////////////BUYER SALES PRICE ////////////
    BUYER_SALES_PRICE_PURCHASE_TYPE_CASH_ID: '1',
    BUYER_SALES_PRICE_PURCHASE_TYPE_PURCHASE_WITH_FINANCE_ID: '2',

    //////////////////Transaction Type////////////
    TRANSACTION_TYPE_PURCHASE_WITH_CASH: '202',
    TRANSACTION_TYPE_REFINANCE: '203',
    TRANSACTION_TYPE_REFINANCE_CASH_OUT: '204',
    TRANSACTION_TYPE_PURCHASE_WITH_FINANCE: '201',

    /////////TITLE Policy paid By/////////////
    TITLE_INSURENCE_DEFAULT: '1',
    TITLE_INSURENCE_50_50: '2',
    TITLE_INSURENCE_BUYER: '3',
    TITLE_INSURENCE_SELLER: '4',
    REFINANCE_0_4_YEARS: '1',
    REFINANCE_4_8_YEARS: '2',
    REFINANCE_MORE_THAN_8_YEARS: '3',

    //////////////MORTGAGE//////////////
    NO_MORTGAGE_ID: '1',
    ONE_OUTSTANDING_MORTGAGE_ID: '2',
    TWO_OUTSTANDING_MORTGAGE_ID: '3',
    FIRST_LOAN_AMOUNT_ID: '1',
    SECOND_LOAN_AMOUNT_ID: '2',

    /////////////Commission///////////
    BUYER_THREE_PERCENTAGE_COMMISSION_ID: '1',
    BUYER_CUSTOM_COMMISSION_RATE_ID: '2',
    BUYER_CUSTOM_AMOUNT_COMMISSION_ID: '3',
    LISTING_THREE_PERCENTAGE_COMMISSION_ID: '1',
    LISTING_CUSTOM_COMMISSION_RATE_ID: '2',
    LISTING_CUSTOM_AMOUNT_COMMISSION_ID: '3',

    ////////////////HOA//////////////
    NO_HOA_ID: '1',
    MONTHLY_HOA_ID: '2',
    QUARTERLY_HOA_ID: '3',
    ANUAL_HOA_ID: '4',
    YES_HOA_DUE_ID: 'Yes',
    NO_HOA_DUE_ID: 'No',
    YES_HOA_DUE_VALUE: 'Yes',
    NO_HOA_DUE_VALUE: 'No',

    //////////Property Tax//////////
    PROPERTY_TAX_RATE_ID: '1',
    PROPERTY_TAX_AMOUNT_ID: '2',

    ////////////////Buyer Sale Price//////////
    BUYER_TITLE_INSURENCE_DEFAULT: '1',
    BUYER_TITLE_INSURENCE_50_50: '2',
    BUYER_TITLE_INSURENCE_BUYER: '3',
    BUYER_TITLE_INSURENCE_SELLER: '4',
    BUYER_PURCHASE_TYPE_CASH: '1',
    BUYER_PURCHASE_TYPE_PURCHASE_WITH_FINANCE: '2',

    ///////////////Loan Type/////////////////////
    LOAN_TYPE_CONVENTIONAL_ID: '1',
    LOAN_TYPE_VA_ID: '2',
    LOAN_TYPE_FHA_ID: '3',
    LOAN_TERM_30_YEARS_ID: '1',
    LOAN_TERM_15_YEARS_ID: '2',
    LOAN_TERM_20_YEARS_ID: '3',
    LOAN_STANDARD_20_PERCENTAGE_ID: '1',
    LOAN_CUSTOM_PERCENTAGE_ID: '2',
    LOAN_CUSTOM_AMOUNT_ID: '3',
}