export const constantValues = {
    GOOGLE_PLACE_API: 'https://maps.googleapis.com/maps/api/place/autocomplete/json?',
    GOOGLE_API_KEY: 'AIzaSyDao5jHYWwwCyJPmIf_qFlWVvSvUePHM_4',
    APPLICATION_TITLE: 'BillionBrix',
    BASE_URL: 'http://localhost:3000/',
    BASE_URL1: 'http://ec2-3-145-213-17.us-east-2.compute.amazonaws.com:8081/',
    INPUT_DETAILS: 'input',
    INPUT_DETAILS1: 'titlecalculatorservice/get-company-details',
    SELLER_NET_SHEET_INPUT_DETAILS: 'sellernetsheetinput',
    VIRTUAL_ASSISTANT: 'Hi, I\'m Sophie, your Virtual escrow assistant',
    LOCATION_INSTRUCTION: 'Let\'s get you a quote in seconds! I\'m ready when you are',
    TRANSACTION_TYPE_INSTRUCTION: 'Great! We found your property. Just few more steps to go!',
    INSURENCE_PAID_INSTRUCTION: 'Got it! Please tell me who pays for owner\'s Title Policy',
    AMOUNT_INSTRUCTION: 'Oh! We are at last stage now!!!',
    BRANCH_DROPDOWN_LABEL1 : 'First, tell me which branch of ',
    BRANCH_DROPDOWN_LABEL2 : ' is handling your closing',
    LOCATION_LABEL : 'What\'s the property address?',
    TRANSACTION_TYPE_LABEL: 'Tell me about your transaction Type',
    INSURENCE_PAID_LABEL: 'Who pays for Owner\'s Title  policy',
    REFINANCE_LABEL: 'How old!!!',
    MORTGAGE_INSTRUCTION: 'Awesome! Let\'s continue with just a few more data points.',
    COMMISSION_INSTRUCTION: 'Few More steps to go.',
    HOA_INSTRUCTION: 'Few More steps to go.',
    PROPERTY_TAX_INSTRUCTION: 'Almost there! Let me know about your property tax',
    OTHER_INFO_INSTRUCTION: 'Ready to get your estimation! Please hit the Calculate button. But before that check if you have any other expanses'
}